### ISSUE TITLE
Nowe pole "device" - data zakupu / wyceny

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#11]
To ma sens księgowy - czasem kupujemy rzeczy nowe, czaem używane - warto wiedzieć, czy te 3 tysie to zapłaciliśmy za nówkę / używkę i kiedy - jeśli minęły dwa lata, to sprzęt jest pewnie wart sporo mniej.

**Comment by Darez** [comment]
zrobione
