### ISSUE TITLE
Nowy typ wypożyczenia - do osoby (nie lokalizacji)

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#14]
Wypożyczenia do osoby z definicji muszą być czasowe z limitem automatycznym - 2 tygodnie i możliwością przedłużania w nieskończoność o tydzień. System rozsyła przypomnienia w momencie jak kończy się limit do osoby wypożyczającej z zapytaniem czy już odda, czy chce przedłużyć. Chęć przedłużenia musi klepnąć "zastępowy".

**Comment by kamilsi** [comment]
Obowiązkowe do wypełnienia pole objaśniające co dzieje się ze sprzętem (co za projekt)

**Comment by draffter** [comment]
Przy zamknięciu ORDER określamy, czy leży u człowieka, czy w DOJO. Nie ma zastępowego, mail na ogólny zarządu

**Comment by Darez** [comment]
Została do zrobienia wysyłka maili. Zajmę się tym jutro.

**Comment by kamilsi** [comment]
Super, propsy :-)
11 wrz 2015 19:25 "Darez" <notifications@github.com> napisał(a):

**Comment by Darez** [comment]
Zostaje problem do kogo słać maile. Na tą chwilę dorobię dodatkowe uprawnienie, którym oznaczę osoby które będą brane pod uwagę. Jeśli to nie będzie miało zastosowania to pomyślimy o tym na spotkaniu,

**Comment by Darez** [comment]
done

**Comment by kamilsi** [comment]
Mamy w lokalizacji Zambrów zasób (HAR39), który próbowałem przypisać teraz konkretnie do siebie (wypożyczyć do domu). Nie widzę tego zasobu na liście możliwych do wypożyczenia.

**Comment by draffter** [comment]
Bug jest zamknięty, ale soft jeszcze nie jest na serwerze (wersja 0.3.0) stąd możesz mieć problem z wypożyczeniem - teraz teoretycznie jest u Ciebie.
