### ISSUE TITLE
Raport: sprzęt "w ludziach"

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#16]
Kto ma osobiście sprzęt i jak długo

**Comment by draffter** [comment]
Możliwość przypisania sprzętu do człowieka w ramach lokalizacji. Domyślnie jest przypisanie do osoby odbierającej ORDER. Ta osoba może przepisać do innej osoby. Czy kolejne przepisanie może dokonać osoba która go ma?

**Comment by draffter** [comment]
po zamknięciu ORDER status sprzętu zostaje jako zajęty
wzięcie sprzętu nie powoduje zmiany statusu sprzętu, zwolnienie sprzętu trzeba klknąć ręcznie i wtedy można go zamówić.

**Comment by Darez** [comment]
close
