### ISSUE TITLE
Dodać do katalogu config przykładowy plik z konfiguracją

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#23]
np. config.sample.xml

**Comment by Darez** [comment]
Docelowo myślałem o zrobieniu konfiguratora przez www (tak jak mają np gotowe fora), gdzie w formularzu podajesz parametry do bazy, google key itp. Na podstawie tych danych tworzy się plik konfiguracyjny. Chyba takie rozwiązanie będzie lepsze?

**Comment by ldziedziul** [comment]
Jedno drugiemu nie przeszkadza ;)
