### ISSUE TITLE
Błąd podczas uruchamiania aktualizacji aplikacji

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#25]
Kiedy pierwszy raz odpaliłem skrypt to pojawił się jakiś normalny komunikat o zmianie wersji, ale przy kolejnym odpaleniu `./bin/command migrate:update`, pojawił się komunikat: 
```Error in version 20150711112810: The table with name 'c0sms.device_tags' already exists.```

**Comment by Darez** [comment]
Czy proces który wykonuje proces ./bin/command migrate:update ma prawa do zapisu w folderze config?

**Comment by ldziedziul** [comment]
Tak, bo ten sam skrypt kopiuje config.xml do web/config

**Comment by Darez** [comment]
Ok już wiem. Po wykonaniu komendy migrate jest tworzony plik config/migrate.prod.txt. Jest tam zapisany aktualny stan bazy. Ten plik też musi być przenoszony. W sumie to wystarczy jak nie będziemy usuwać plików przy każdym update, tylko je nadpisywać.

**Comment by ldziedziul** [comment]
OK, wyłączyłem kasowanie plików, ale nadal pojawia się ten błąd. 

Jeszcze pytanie co z plikami, które z czasem będą zbędne? Czy migrate zadba o ich skasowanie?

**Comment by Darez** [comment]
Migrate nie usunie niepotrzebnych plików. Jednak nawet jak na serwerze zostaną śmieci to nic się nie stanie. Aby migrate działał poprawnie trzeba stworzyć plik config/migrate.prod.txt z wartością 20150722191210
Ten plik przechowuje informacje o aktualnym stanie bazy więc nie można go modyfikować ręcznie.

**Comment by ldziedziul** [comment]
OK. Dorzuciłem go
