### ISSUE TITLE
prośba o uprawnienia

### ISSUE THREAD

**Issue by draffter** [CoderDojoPL/cd-sms#26]
Zmiana kluczy do Google API. Obecnie aplikacja żądająca uprawnień przedstawia się jako "Jenkins Server" Do zmiany. @Darez czy klucze są nasze testowe, czy już Fundacji?

**Comment by ldziedziul** [comment]
Ja ustawiłem swoje klucze. W wolnej chwili podmienię

**Comment by ldziedziul** [comment]
klucze poprawione
