### ISSUE TITLE
Wersja w stopce

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#27]
Moglibyście dorobić info o aktualnej wersji w stopce strony? Chciałbym szybko widzieć czy aktualizacje robią się prawidłowo ;)

**Comment by draffter** [comment]
Kwestia ustalenia jak numerujemy wersje: x.y.z , gdzie x-milestone, y-new feature, z-bugfix, czy jakoś inaczej?

**Comment by ldziedziul** [comment]
SemVer jest ok (http://semver.org). Może trzymajmy się takiego podziału: x - breaking changes, y-new feature, z-bugfix. Na razie wszystko jest na tyle płynne, że proponuję, abyśmy mieli wersję 0.y.z. Gdy dojdziemy już do jakiejś stabilnej wersji API, możemy zrobić 1.0.0.

**Comment by draffter** [comment]
Dodałem info o wersji i licencji. Ustawiłem MIT, bo albo mi się ubzdurało, albo taką ustaliliśmy :)

**Comment by ldziedziul** [comment]
Na stronie będzie dopiero jak zrobicie pull request i merge do mastera
