### ISSUE TITLE
Automatycznie przełączenie strony na https

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#29]
Fajnie by było, gdyby strona nawet po wejściu na adres http://stuff.coderdojo.org.pl przekierowywała się na bezpieczny adres https://stuff.coderdojo.org.pl/

**Comment by Darez** [comment]
Tyle, że takie rzeczy robi się w konfiguracji serwera. Jeśli jest tam apache to tutaj jest opis:
https://wiki.apache.org/httpd/RedirectSSL

**Comment by ldziedziul** [comment]
Widziałem parę aplikacji, które umożliwiały to z poziomu aplikacji, ale spoko ustawię na serwerze.

**Comment by ldziedziul** [comment]
Zrobione przy pomocy mod_rewrite
