### ISSUE TITLE
Log o zmianie lokalizacji

### ISSUE THREAD

**Issue by draffter** [CoderDojoPL/cd-sms#30]
Nie ma niestety kolumny jaka lokalizacja na jaką się zmieniła
![image](https://cloud.githubusercontent.com/assets/1515356/8926460/2d727e6a-3510-11e5-878e-0d223d3d7a26.png)

**Comment by kamilsi** [comment]
Ja wybrałem pierwszą lokalizację po zalogowaniu się, więc zmieniłem z
żadnej na default.
