### ISSUE TITLE
Fotografie nie wyświetlają się w widoku "devices"

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#32]

**Comment by Darez** [comment]
Wrzuciłem testowy produkt i jest ok (na 2 stronie jest widoczny). Możesz załączyć plik ze zdjęciem który się nie chce wyświetlać?

**Comment by kamilsi** [comment]
W dniu 18 sierpnia 2015 21:21 użytkownik Darez <notifications@github.com>
napisał:

> Wrzuciłem testowy produkt i jest ok (na 2 stronie jest widoczny). Możesz
> załączyć plik ze zdjęciem który się nie chce wyświetlać?


Mi się kompletnie nic nie wyświetla:

[image: Obraz w treści 1]

**Comment by draffter** [comment]
Wrzuciłem plik z obrazem do chrombooka #2, zobacz, czy widzisz
faktycznie pozostałe urządzenia nie mają obrazków (oprócz testowego, ten również ma)

**Comment by kamilsi** [comment]
Faktycznie działa, można zamknąć ☺
