### ISSUE TITLE
Można przenieść sprzęt bez wiedzy tego kto go posiada

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#35]
Franek niechcący zhakował naszą apkę - https://stuff.coderdojo.org.pl/order/show/1 - samodzielnie zamawiając i potwierdzając, że dostał Oculus Rifta (tak naprawdę nie dostał). Potem ja bez żadnej interakcji z nim zamówiłem i potwierdziłem odbiór w Zambrowie.
Trzeba:
1. wprowadzić powiadomienia dla osób, które mają sprzęt nadać, że jest żądanie wysyłki
2. wprowadzić stan pośredni i potwierdzenie wysłania (teraz jest zażądaj --> potwierdź, powinno być zażądaj --> wysyłający potwierdza wysyłkę lub odmawia --> anulowanie lub potwierdź odbiór).

**Comment by Darez** [comment]
Błąd usunięty bez dodania powiadomień (to zrobimy w przyszłości, jak dodamy obsługę notyfikacji). Anulowanie zamówienia też zostawiamy na później.
