### ISSUE TITLE
Podstawowy uzytkownik nie może wykonać żadnej akcji

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#41]
Podstawowy użykownik wdzi tylko sekcję "my devices", przez co nie może ani przejrzeć, ani zamówić sprzętu - powinien przynajmniej móc przejrzeć listę całego sprzętu (do odczytu) i zrobić zamówienie (i potem je procesować)

**Comment by Darez** [comment]
Niektórzy użytkownicy nie mieli przypisanej roli. Zakładam, że te osoby zgłaszały problem. Przypisałem im role "Użytkownik". Prośba o ponowne sprawdzenie.

**Comment by DonatSasin** [comment]
Proszę o dodanie roli dla d.sasin

**Comment by kamilsi** [comment]
Trzeba też domyślnie nadawać wszystkim rolę "user"

**Comment by Darez** [comment]
Dopiero teraz zauważyłem ten komentarz... Nadałem.
Na przyszłość to sami możecie to robić (Managment->Users->Edit)

**Comment by kamilsi** [comment]
Byłoby świetnie gdyby można było zdefiniować rolę jaka nadawanabyłaby
domyślnie wszystkim nowym użytkownikom
