### ISSUE TITLE
Nie można samodzielnie zainicjować transferu sprzętu

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#42]
Jedyny sposób w jaki można "pozbyć się" przętu to poprosić kogoś z lokalizacji docelowej, aby go zamówił - ja sam nie jestem w stanie np. oddać sprzętu, który mam na stanie.

**Comment by Darez** [comment]
Mowa tutaj o oddaniu sprzętu który jest przypisany do Ciebie i chcesz wrzucić go do puli lokalizacji do której należy Twój użytkownik?
Czy druga opcja, czyli komuś chcesz przekazać sprzęt, ale to Ty chcesz wystawić zlecenie, a nie osoba która ów urządzenie ma otrzymać?

**Comment by kamilsi** [comment]
> Mowa tutaj o oddaniu sprzętu który jest przypisany do Ciebie i chcesz
> wrzucić go do puli lokalizacji do której należy Twój użytkownik?
>
Mi chodziło o pierwszą

**Comment by Darez** [comment]
Zrobione. Prośba o przetestowanie

**Comment by kamilsi** [comment]
Nie, nie działa :-(

**Comment by Darez** [comment]
Dorzuciłem przycisk do przekazania sprzętu w ramach lokalizacji (Device->My->Assign to location)
