### ISSUE TITLE
Aktualizacja konfiguracji na serwerze

### ISSUE THREAD

**Issue by Darez** [CoderDojoPL/cd-sms#43]
Cześć
Prośba o stworzenie i dodanie w pliku config/variables.xml takich wpisów do sekcji content (value trzeba podmienić na wartości z konfiguracji skrzynki mailowej z której mają wychodzić wiadomości):

    <variable name="mail.host" value="host" />
    <variable name="mail.ssl" value="false" />
    <variable name="mail.port" value="port" />
    <variable name="mail.username" value="maill@mail.pl" />
    <variable name="mail.password" value="password" />
    <variable name="mail.fromAddress" value="mail@amil.pl" />

    <variable name="www.host" value="https://stuff.coderdojo.org.pl/" />

Bez tego nie mogę zrobić release bo wysypie się produkcja:/

**Comment by ldziedziul** [comment]
Zrobione. Czy te wartości nie mogą być po prostu w config.xml ?
