### ISSUE TITLE
Przypisanie sprzętu do siebie

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#44]
Próbuję wziąć na siebie "Acer Chromebook CB3-111" z nr seryjnym "Lukasz", ale nie widzę go w nowym orderze.

**Comment by kamilsi** [comment]
Na razie jako workaround musisz poprosić kogoś z inengo Dojo żeby to od Ciebie zamówił, a potem Ty od niego.

**Comment by Darez** [comment]
jak to powinno wyglądać? Na liście Device->Location powinien być przycisk za pomocą którego możesz pobrać sprzęt z własnego dojo do siebie?

**Comment by kamilsi** [comment]
Brzmi super 👌

**Comment by Darez** [comment]
zrobione
