### ISSUE TITLE
Błąd przy dodawaniu rodzaju sprzętu

### ISSUE THREAD

**Issue by Darez** [CoderDojoPL/cd-sms#46]
Poprawiłem kod, ale zanim go wrzucę trzeba posprzątać bazę. Prośba o wykonanie tych sql:

delete from device_type_logs where id not in(1,2);
delete from device_types where id not in(1,2);

**Comment by ldziedziul** [comment]
Zrobione

**Comment by Darez** [comment]
Które sql dokładnie wykonałeś? Usunęło wszystkie sprzęty:/. Jak wrzucałem post to rzeczywiście dałem złe sql ale po chwili je poprawiłem. W tej sytuacji trzeba będzie przywrócić z kopi zapasowej:/

**Comment by ldziedziul** [comment]
Wykonałem to co napisałeś:
```
delete from device_type_logs where id not in(1,2);
delete from device_types where id not in(1,2);
```

Nie widziałem innego sql-a. Wrzuciłem kopię, którą wykonałem tuż przed wykonaniem powyższego sql-a

**Comment by Darez** [comment]
Teraz jest ok, zamykam
