### ISSUE TITLE
Nie można oddać sprzętu do Dojo

### ISSUE THREAD

**Issue by kamilsi** [CoderDojoPL/cd-sms#48]
Jak już ma się sprzęt na koncie prywatnym nie można go oddać do Dojo. Udało mi się stworzyć zamówienie na ten sprzęt (sam od siebie zamawiam: https://stuff.coderdojo.org.pl/order/show/11), ale teraz nie mogę go zaakceptować (też bvug?)

**Comment by kamilsi** [comment]
Suplikat z bugiem #42

**Comment by Darez** [comment]
Dzisiaj dorobię możliwość przekazania sprzętu od prywatnej osoby do swojego dojo.

**Comment by Darez** [comment]
poprawione

**Comment by kamilsi** [comment]
Działa! :+1:
