### ISSUE TITLE
Postawić hosting na aplikację

### ISSUE THREAD

**Issue by ldziedziul** [CoderDojoPL/cd-sms#7]

**Comment by kamilsi** [comment]
I domenę - propozycja stuff.coderdojo.org.pl

**Comment by ldziedziul** [comment]
Ustawiłem adres http://stuff.coderdojo.org.pl/

Teraz czekam na instrukcję, aby ewentualnie coś doinstalować lub skonfigurować.

**Comment by ldziedziul** [comment]
@Darez @draffter Czy może być MySQL? Mógłbym wtedy wyklikać całą konfigurację :)

**Comment by Darez** [comment]
Wymagane pakiety:
-php w wersji minimum 5.3 (zalecane 5.4 lub 5.5 bo wcześniejsze nie są oficjalnie wspierane, a w przyszłości jak będziemy korzystać z gotowych bibliotek, może okazać się że nie pójdą na starszych wersjach interpretera).
-php-pdo - do bazy danych+jakiś sterownik (php-pg lub php-mysql).
-php-gd (jeszcze w tym momencie nie jest wymagany, ale zaraz będzie)

Ustawienia:
w php.ini ustawić timezone - http://php.net/manual/pl/datetime.configuration.php#ini.date.timezone
dodać vhost. Wklejam poniżej z apache (nie wiem z czego korzystacie więc poniżej dorzuciłem komentarze):
<VirtualHost *:80>
        ServerAdmin mail@admina
        ServerName hms.iteracja.com
        DocumentRoot /var/www/hms/web #document root musi wskazywać na folder web w projekcie
        <Directory /var/www/hms/web> #dla document root
           AllowOverride All #musi być nadane uprawnienie do wykonywania plików .htaccess (jeśli na serwerze jest nginx to ten link się przyda http://winginx.com/en/htaccess aby przerobić rewrite z pliku web/.htaccess) 
           Allow from all #pełny dostęp do folderu
        </Directory>

</VirtualHost>

Oprócz tego trzeba stworzyć bazę +user z pełnymi uprawnieniami do wszystkich operacji (no może bez drop/create database). Wymagane dla automatycznej migracji stanów bazy.

I na koniec wrzucić plik konfiguracyjny projektu czyli do folderu config w root projektu:

<?xml version="1.0" ?>

<content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <variable name="prod.database.driver" value="pdo_pgsql" /> 
    <variable name="prod.database.host" value="127.0.0.1" />
    <variable name="prod.database.user" value="root" />
    <variable name="prod.database.password" value="secret" />
    <variable name="prod.database.dbname" value="hms" />


    <variable name="prod.google.clientId" value="secret" /> 
    <variable name="prod.google.clientSecret" value="secret" />
    <variable name="prod.google.redirectUri" value="secret" />

</content>
Do folderu config użytkownik, który będzie robił update musi mieć możliwość zapisu i odczytu (migrate w nielicznych sytuacjach może modyfikować pliki konfiguracyjne).

Aktualizacja projektu:
Chyba najlepiej będzie jak do branch master będziemy wrzucać przetestowaną wersję produkcyjną więc wystarczy git pull. Po tym zawsze trzeba odpalić komendę ./bin/command migrate:update folder bin znajduję się w root projektu.

To chyba wszystko.

**Comment by ldziedziul** [comment]
Serwer wstępnie ustawiony: jest php 5.4. Jak wrzucicie kod do repo to przetestuję czy działa.

**Comment by Darez** [comment]
Dopiero teraz zauważyłem powiadomienia z tego issue. Kod zdążyłem wrzucić już wczoraj.

**Comment by ldziedziul** [comment]
Strona działa pod adresem http://stuff.coderdojo.org.pl/ 

Czekam tylko jescze na certyfikat SSL, powinien być najdalej w poniedziałek.

**Comment by ldziedziul** [comment]
Wgrałem certyfikat SSL
